nelmio_api_doc:
    documentation:
        info:
            title: Api BileMo
            description: La meilleure des API pour nos meilleurs clients ! 
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
